services:
  postgres:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: mini_bank_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mini_bank_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/dashboards/all:/etc/grafana/provisioning/dashboards/all
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

#  mini-bank-app:
#    image: ghcr.io/ashish-thakur111/mini-bank:latest
#    container_name: mini_bank_app_container
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mini_bank_db
#      SPRING_DATASOURCE_USERNAME: mini_bank_user
#      SPRING_DATASOURCE_PASSWORD: password123
#    depends_on:
#      - postgres
#      - prometheus
#      - grafana
